// Generated by scripts/embed-skills.sh from ai/**/SKILL.md. Do not edit.
//
// Run `scripts/embed-skills.sh` after touching a SKILL.md; CI fails the build
// if this file and its source have drifted (`scripts/embed-skills.sh --check`).
// Committed rather than generated at build time so an `xcodebuild` from a
// release tarball needs no shell script to have run first.

/// Perch's agent skills, baked in — see `Skills.swift` for what `perch skill`
/// does with them. Raw string literals (`#"""`), so the backslashes and pipes
/// in a markdown table survive verbatim; the trailing newline of each source
/// file is the one byte the literal cannot carry, and `Skills` puts it back.
enum GeneratedSkills {
    struct Skill {
        let name: String
        /// The file's bytes, minus its single trailing newline.
        let body: String
    }

    /// The tool's own skill is first: `perch skill` with no name prints it.
    static let all: [Skill] = [
        Skill(
            name: "perch",
            body: #"""
---
name: perch
description: Put files on the Mac's notch shelf — the tray that lives in the screen's notch and holds things you're about to drag somewhere — and read or prune what's already there. Use when the user says "put this in my shelf", "add this to perch", "shelf this", "hold onto this file", "stick that on the notch", "park these screenshots somewhere I can drag them", "what's on my shelf", "take that off the shelf", "clear my shelf", or hands you a file and asks you to keep it handy. Also when they ask why the shelf isn't working, or for perch's version.
---

# Perch — the notch file shelf

Perch is a macOS app that turns the notch into a shelf. Files land there as
tiles; the user drags them out into whatever app wants them. It's the halfway
house between "I have this file" and "this file needs to go over there" —
especially across apps that don't share a file picker.

You reach it with the `perch` command: `add` puts files on the shelf, `list`
says what's on it, `rm` takes things off, and `doctor` says whether any of that
can work on this Mac.

Perch must be running for the first three. If it isn't, each of them launches it
and keeps waiting — you don't have to start it yourself. `doctor` and `skill`
are the exceptions: they answer with no shelf running, and `doctor` deliberately
never starts one.

## Verbs

| do this | run this |
|---|---|
| put files on the shelf | `perch add report.pdf shot.png` |
| shelf a whole pipe of paths | `find . -name '*.png' -newermt '1 hour ago' \| perch add -` |
| see what's on the shelf | `perch list` |
| read the shelf as data | `perch list --json` |
| take one item off | `perch rm <item-id>` |
| clear the shelf (pins survive) | `perch list --json \| jq -r '.items[] \| select(.pinned \| not) \| .id' \| perch rm -` |
| shelf something and read the result | `perch add --json build/app.zip` |
| shelf quietly (scripts) | `perch add -q <path>...` |
| refuse to auto-launch Perch | `perch add --no-launch <path>...` |
| wait longer than 15s for a slow launch | `perch add --wait 30 <path>...` |
| find out why the shelf isn't working | `perch doctor` |
| read that as data | `perch doctor --json` |
| get perch's version and this Mac's, for a bug report | `perch doctor` — its first two lines carry every fact the form's diagnostics field asks for |
| print this skill | `perch skill` |
| install this skill for every agent client on the Mac | `perch skill install` |
| everything, exhaustively | `perch --help` (**not** `perch add --help` — that's a usage error) |

Paths after `--` are always treated as paths, however they're spelled. `-` on
its own reads newline-separated operands from stdin — paths for `add`, ids for
`rm`.

`perch list` prints one line per tile, **id first**, because the id is what `rm`
takes. `rm` never takes a name: two tiles can share one, and it won't guess.

## Reading the JSON

`add` prints `{"added":[…],"refused":[…],"failed":[…]}`, each entry
`{name, path}` (plus `reason` on the last two). `path` is your own argument
resolved and echoed back on your own stdout; it is never sent to Perch, which
only ever learns the display name.

`list` prints `{"items":[…]}` and `rm` prints `{"removed":[…],"missing":[…]}`,
where an item is `{id, name, kind, contentType, bytes, addedAt, pinned}` —
every key always present, `contentType` and `bytes` null when Perch doesn't
know them. `missing` holds the ids that didn't come off the shelf, and under
`--json` it is the *only* place they are reported. There is no path in any of
it: where the bytes live is the app's business.

## `doctor` — the first thing to run when something is wrong

`perch doctor` needs nothing running. It prints perch's version and install
(Homebrew cask, haus desktop, Nix store path, release ZIP — they update
differently and that is usually the answer), this Mac's macOS and model, whether
the shared container exists, and whether a shelf answers. `✓` fine, `!` worth
knowing, `✗` blocking; exit 3 means at least one `✗`.

A `!` on the `shelf` line can mean "running, but too old to read the shelf" —
that Perch answers `add` and not `list`, and only an update fixes it.

Read the `install` line before telling anyone how to update perch — the right
command is `brew upgrade --cask perch`, `haus update`, a flake bump or a
one-click in the app, and only doctor knows which.

## Exit codes — check these, they mean different recoveries

| | meaning | what to do |
|---|---|---|
| 0 | it worked: paths landed / the shelf was printed / the items are off it | say what's on the shelf now |
| 1 | usage error, a path that doesn't exist, an id that didn't come off the shelf, or a skill name perch doesn't ship | fix it; for `add` **nothing was submitted**, for `rm` the *other* ids were still removed |
| 2 | Perch turned items away — or `skill install` found a `SKILL.md` that differs and left it alone | report it; don't retry the same batch. Nothing on the shelf refuses today, so from `add` this means something new is happening |
| 3 | no Perch answered in time, Perch has never been opened on this Mac, **or** the Perch running is older than the verb — from `doctor`, something blocking | read the message: "older than `list`" means the app needs updating, nothing else will help. Otherwise retry with `--wait 30`, then the user must launch Perch once by hand |
| 4 | the exchange broke — for `add`, the items were admitted and a copy failed; for `skill install`, a file couldn't be written | check the source is readable; partial batch |

An `add` batch containing one bad path is refused **whole**, before anything is
submitted. So a `1` from `add` never means "some of them made it". An `rm`
batch is refused whole only if an argument isn't a UUID at all.

## When to reach for this

- "put this in my shelf" / "shelf these" / "add this to perch" → `perch add`
- "hold onto this for a sec" / "I want to drag this into Slack in a minute" →
  `perch add`, and say the tile is on the notch
- "put all the screenshots from this morning on my shelf" → pipe `find` into
  `perch add -`
- "what's on my shelf" / "is that still there" → `perch list`
- "take that off" / "clear the shelf" → `perch list --json` to find the id,
  then `perch rm`
- "the shelf isn't taking anything" / "perch is broken" / "what version am I
  on" → `perch doctor`, and read its `✗` and `!` lines out loud
- "teach my other agent about perch" / "install the perch skill" →
  `perch skill install`

## When NOT to

- **The user wants the file somewhere permanent.** The shelf is a staging tray,
  not a folder. Copy or move it instead.
- **The user wants a notification.** That's `trill send`.
- **The user wants to change how Perch behaves** (whether it's installed, where
  it sits) — that's a haus setting, `haus.shelf.*`, not this command.
- **You are on Linux or in a container.** Perch is macOS-only and needs a
  logged-in GUI session; there is no headless mode.

## Traps

- **`rm` is not undo.** It deletes the copy Perch staged, and there's no
  putting it back from here. Confirm before clearing a shelf you didn't fill.
- **A pinned tile is pinned for a reason** — it stays put through a drag so the
  user can drop it again. `perch list` marks it; `rm` will still remove one if
  you name its id, so don't sweep pins into a "clear the shelf".
- **Perch never touches the original.** It reads and copies — and `rm` only
  ever removes its own copy. So "shelf this and delete the original" is two
  steps, and the second one is yours: do it only if asked, and only after exit 0.
- **Never pass a path Perch itself has to open.** The command reads the bytes
  and hands them over; there is no URL scheme, and `perch://add?path=…` does
  not exist. Perch is sandboxed and could not open such a path anyway.
- **Exit 0 with `--quiet` prints nothing.** That's success, not a hang.
- **`doctor` will not start Perch,** on purpose — a doctor that starts the
  patient can't report on it. A `✗ shelf` line means "not running", not "broken".
- **`skill install` refuses rather than clobbers.** On a haus machine every
  target is a read-only symlink and it leaves them alone and exits 0 — the skill
  is already installed and current. Exit 2 means a real file was there with
  different bytes; don't work around it, tell the user which path.
"""#
        ),
    ]
}
