#!/usr/bin/env bash
# Bake ai/**/SKILL.md into the `perch` tool, as Swift.
#
# The family standard (workshop docs/agent-surface.md, A3) says `<tool> skill`
# prints the skill from **inside the binary**, not off disk. Perch ships through
# a cask (an `.app` somebody drags), a Nix store path (read-only) and a raw
# release ZIP, and the tool itself is only ever a symlink into the bundle — so
# every "read it from beside me" scheme is right for one of those and wrong for
# the others. A string literal is right for all three, and it makes the version
# that answers `--version` the version that answers `skill`.
#
# The generated file is COMMITTED, not built on the fly: the Xcode project has
# no script phase for the CLI, and adding one would make an `xcodebuild` from a
# release tarball depend on a shell script that may not have run. Committing it
# costs one guard instead — `--check`, which CI runs — and that guard is the
# whole reason this is a script rather than a habit.
#
# Usage:
#   scripts/embed-skills.sh            rewrite PerchCLI/GeneratedSkills.swift
#   scripts/embed-skills.sh --check    fail if the committed copy is stale
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tool=perch
out="$root/PerchCLI/GeneratedSkills.swift"

check=0
case "${1:-}" in
"") : ;;
--check) check=1 ;;
*) printf 'usage: embed-skills.sh [--check]\n' >&2; exit 2 ;;
esac

[ -f "$root/ai/SKILL.md" ] || {
  printf 'embed-skills.sh: no ai/SKILL.md — nothing to embed\n' >&2
  exit 2
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'HEAD'
// Generated by scripts/embed-skills.sh from ai/**/SKILL.md. Do not edit.
//
// Run `scripts/embed-skills.sh` after touching a SKILL.md; CI fails the build
// if this file and its source have drifted (`scripts/embed-skills.sh --check`).
// Committed rather than generated at build time so an `xcodebuild` from a
// release tarball needs no shell script to have run first.

/// Perch's agent skills, baked in — see `Skills.swift` for what `perch skill`
/// does with them. Raw string literals (`#"""`), so the backslashes and pipes
/// in a markdown table survive verbatim; the trailing newline of each source
/// file is the one byte the literal cannot carry, and `Skills` puts it back.
enum GeneratedSkills {
    struct Skill {
        let name: String
        /// The file's bytes, minus its single trailing newline.
        let body: String
    }

    /// The tool's own skill is first: `perch skill` with no name prints it.
    static let all: [Skill] = [
HEAD

  emit() {
    name="$1" path="$2"
    # `"""#` on a line of its own would close the literal early. Nothing in a
    # SKILL.md needs it, and a build that mis-parses is worse than a refusal.
    if grep -q '"""#' "$path"; then
      printf 'embed-skills.sh: %s contains `"""#`, which would close the Swift literal\n' "$path" >&2
      exit 1
    fi
    printf '        Skill(\n            name: "%s",\n            body: #"""\n' "$name"
    cat "$path"
    printf '"""#\n        ),\n'
  }

  emit "$tool" "$root/ai/SKILL.md"
  for dir in "$root"/ai/*/; do
    [ -f "$dir/SKILL.md" ] || continue
    emit "$(basename "$dir")" "$dir/SKILL.md"
  done

  cat <<'TAIL'
    ]
}
TAIL
} >"$tmp"

if [ "$check" = 1 ]; then
  if cmp -s "$tmp" "$out"; then
    exit 0
  fi
  printf 'embed-skills.sh: PerchCLI/GeneratedSkills.swift is stale — run scripts/embed-skills.sh\n' >&2
  diff -u "$out" "$tmp" >&2 || true
  exit 1
fi

cp "$tmp" "$out"
printf 'wrote %s\n' "${out#"$root"/}"
